### PR TITLE
Issue 787 fix issue with asset search bar height and some issues

### LINKED ISSUE #787: Fix: Issue with asset search bar height
# ℹ Overview
Asset search bar height not updated correctly

### LINKED ISSUE #795: Fix: When I hover over unpriced assets, the names are undefined
# ℹ Overview

image

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fixes issues
- Height of search bar
- Place order form price, amount and total precision
- Asset name on hover in search flyout
- Line spacing around asset description in asset info

### 📝 Related Issues
- closes #787 
- closes #795 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/Wallet/PlaceOrder/Form.jsx [hunk 1]
```diff
@@ -88,8 +88,16 @@ export function PlaceOrderForm({ showTitle = true, asset, onSubmit, components:
     submitting: false
   })
 
+  const formatFloat = (value, decimal=6) => {
```
Comment (atrefonas) [inline components/Wallet/PlaceOrder/Form.jsx]: Very minor but I think put this in a useCallback?

File: components/Nav/SearchSidebar/SearchTable.jsx [hunk 2]
```diff
@@ -206,6 +206,7 @@ export const NavSearchTable = ({
       setTimeout(() => {
         if (searchTableRef?.current) {
           const { width, height } = searchTableRef.current.getBoundingClientRect()
+          console.log('Search height:', height)
```
Comment (atrefonas) [inline components/Nav/SearchSidebar/SearchTable.jsx]: Do you want this console.log to go onto Production?

**Review by atrefonas — CHANGES_REQUESTED** [review]
Overall looks good.

However, you should not be able to type in an amount larger than you can afford (which would also be over 100% of the bar).

If you type in a large number, it should auto-adjust the number downwards to be the 100% of the bar.

image
