### PR TITLE
:zap: Update toast message, catch error if any on token creation

### LINKED ISSUE #960: Improve styling for toast message
# ℹ️ Overview 
Improve the wording and styling of the toast messages for creating a token. The end result should look and feel the same as the loading messages for placing an order on algodex

### LINKED ISSUE #961: Add error handling to CreateToken component
# ℹ️ Overview 
Add error handling for when form inputs are valid but transaction fails anyway

### PR DESCRIPTION
**Pull request by treasurechic**
# ℹ Overview

### 📝 Related Issues

closes #960 
closes #961 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/LaunchPad/Token/CreateToken.tsx [hunk 1]
```diff
@@ -232,9 +228,19 @@ export const CreateToken = () => {
...
     }
     // toast.loading('AWAITING SIGNATURE', { duration: 30 * 60 * 1000 })
-    createAsset(formData, algodex.algod, activeWallet, notifier).then(
-      (asset) => (lastToastId = toast.success('sucess'))
-    )
+    createAsset(formData, algodex.algod, activeWallet, notifier)
+      .then((asset) => {
+        setLoading(false)
+        lastToastId = toast.success('sucess')
+        setLoading(false)
```
Comment (ericsharma) [inline components/LaunchPad/Token/CreateToken.tsx]: Looks pretty good to me was just wondering why we set loading to false twice if `createAsset()` was successful

**Review by ericsharma — CHANGES_REQUESTED** [review]

File: components/LaunchPad/Token/CreateToken.tsx (hunk 1 above)
Comment (treasurechic) [reply components/LaunchPad/Token/CreateToken.tsx]: That is a mistake, will remove it

**Review by ericsharma — APPROVED** [review]
