### PR TITLE
Issue 774 acceptance fix asset price in available balance

### LINKED ISSUE #774: Acceptance: Fix asset price in available balance
# ℹ Overview
image
image

Asset price should show correct value

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix issue with asset balance

### 📝 Related Issues
- closes #774 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
USD value = price_of_algos * price_of_asset_in_algos * amount

File: components/Wallet/PlaceOrder/Form/AvailableBalance.jsx [hunk 1]
```diff
@@ -65,12 +66,13 @@ const IconButton = styled.button`
 
 export const AvailableBalance = ({ wallet, asset }) => {
   const { t } = useTranslation('place-order')
+  const price_info = asset?.price_info
   const assetBalance = useMemo(() => {
```
Comment (atrefonas) [inline components/Wallet/PlaceOrder/Form/AvailableBalance.jsx]: Can you rename this from assetBalance to something else?

**Review by atrefonas — APPROVED** [review]

File: components/Wallet/PlaceOrder/Form/AvailableBalance.jsx (hunk 1 above)
Comment (IYTEC) [reply components/Wallet/PlaceOrder/Form/AvailableBalance.jsx]: Renaming to `assetValue`
