### PR TITLE
Issue 870 fix issue with typing decimal for asset amount

### LINKED ISSUE #870: Fix: Issue with typing decimal for asset amount
# ℹ Overview
When user type .(dot) into asset amount in place order trade input form, it shows as 0

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix decimal issue in amount field in trades input form

### 📝 Related Issues
- closes #870 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/Wallet/PlaceOrder/Form.jsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ export function PlaceOrderForm({ showTitle = true, asset, onSubmit, components:
     const amount = getAdjOrderAmount(currentState)
 
     // Amount should be based on asset decimals
-    // currentState.amount = formatFloat(amount, asset.decimals) || ''
+    currentState.amount = formatFloat(amount, asset.decimals) || ''
```
Comment (atrefonas) [inline components/Wallet/PlaceOrder/Form.jsx]: I don't think this is a good solution - can you find a different one? We shouldn't be changing the amount field as you type it as it causes other weird behavior.

**Review by atrefonas — CHANGES_REQUESTED** [review]
See comment.

File: components/Wallet/PlaceOrder/Form.jsx (hunk 1 above)
Comment (IYTEC) [reply components/Wallet/PlaceOrder/Form.jsx]: Okay, I can change the solution, and update from the input itself.

**Review by atrefonas — APPROVED** [review]
