### PR TITLE
🐛 Fix issue with place order price and amount input field

### LINKED ISSUE #778: Fix: Fix address input 0 field
# ℹ Overview
Input field should use Placeholder for empty order amount

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix issue with Decimal in place order input form

### 📝 Related Issues
- closes #778 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

**Review by atrefonas — CHANGES_REQUESTED** [review]
when I delete the amount, I can't type .56

**Comment by atrefonas** [comment]
image

File: components/Wallet/PlaceOrder/Form.jsx [hunk 1]
```diff
@@ -245,25 +245,33 @@ export function PlaceOrderForm({ showTitle = true, asset, onSubmit, components:
...
+  const formatFloat = (price) => {
+    const splited = price.toString().split('.')
+    if (splited[1] && splited[1].length > 6) {
+      return price.toFixed(6)
+    }
+    return price
+  }
+
   // Fix Precision
   useEffect(() => {
```
Comment (atrefonas) [inline components/Wallet/PlaceOrder/Form.jsx:257]: It looks like you have an empty useEffect

**Review by atrefonas — CHANGES_REQUESTED** [review]
The amount field works better, but when I type a price and amount, the total does not update

image

**Review by atrefonas — APPROVED** [review]
