### PR TITLE
Issue 874 fix trade input fields should use asset decimals

### LINKED ISSUE #874: Fix: Trade input fields should use asset decimals
# ℹ Overview
Trade input fields should use asset decimals in field and deleting should not jump
Fix Launch App button text for other languages in about page

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix issue with input field decimals

### 📝 Related Issues
 - closes #874 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/Wallet/PlaceOrder/Form/TradeInputs.jsx [hunk 1]
```diff
@@ -196,15 +196,14 @@ export const TradeInputs = ({
         id="amount"
         name="amount"
         placeholder='0.00'
+        decimals={6}
```
Comment (atrefonas) [inline components/Wallet/PlaceOrder/Form/TradeInputs.jsx]: Hi @IYTEC , the asset needs to use the asset decimals, so wondering why this is now hardcoded to 6? For example an asset might have 0 decimals or 8 decimals.

**Review by atrefonas — CHANGES_REQUESTED** [review]

File: components/Wallet/PlaceOrder/Form/TradeInputs.jsx (hunk 1 above)
Comment (IYTEC) [reply components/Wallet/PlaceOrder/Form/TradeInputs.jsx]: Yes, correct @atrefonas , it should use the asset decimal for amount, I hardcoded while debugging, adding it back now
