### PR TITLE
Issue 1022 fix issue with switching asset

### LINKED ISSUE #1022: Fix: Issue with Switching asset
# ℹ Overview
Fix switching wallet bug on development

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix issue with switching assets

### 📝 Related Issues
- closes #1022 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/Nav/SearchSidebar/SearchSidebar.jsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ import { useRouter } from 'next/router'
 import useUserStore from 'store/use-user-state'
 import { withAlgorandPriceQuery } from '@/hooks'
 import useSearchFilter from '@/hooks/useSearchFilter'
+import { filter } from 'lodash'
```
Comment (ericsharma) [inline components/Nav/SearchSidebar/SearchSidebar.jsx]: Can you delete this import since it is not used?

**Review by ericsharma — CHANGES_REQUESTED** [review]

File: components/Nav/SearchSidebar/SearchSidebar.jsx (hunk 1 above)
Comment (IYTEC) [reply components/Nav/SearchSidebar/SearchSidebar.jsx]: Okay

**Review by ericsharma — APPROVED** [review]
