### PR TITLE
Issue 772 fix show more decimals for the price in open orders and order history

### LINKED ISSUE #772: Fix: Show more decimals for the price in Open Orders and Order History
The price is showing 4 decimals instead of 6.
image

### PR DESCRIPTION
**Pull request by IYTEC**
# ℹ Overview
Fix issue with price decimals in open order, order history and search table

### 📝 Related Issues
- closes #772 

### 🔐 Acceptance:

- [ ] `yarn test` passes

### CODE REVIEW

File: components/Wallet/Table/OpenOrdersTable.jsx [hunk 1]
```diff
@@ -70,12 +71,25 @@ const OrderCancelButton = styled.button`
 export function OpenOrdersTable({ orders: _orders }) {
   // console.log(`OpenOrdersTable(`, arguments[0], `)`)
   const { t } = useTranslation('orders')
-  const [openOrdersData, setOpenOrdersData] = useState(_orders)
+
+  const _formattedOrders = useMemo(() => {
```
Comment (atrefonas) [inline components/Wallet/Table/OpenOrdersTable.jsx]: Can you combine _orders and _formattedOrders into a single useState or useReducer? I think it might be incorrect also since the _orders are set after the _formattedOrders so the state isn't getting updated right away for the formatted orders.

**Review by atrefonas — CHANGES_REQUESTED** [review]

**Review by atrefonas — CHANGES_REQUESTED** [review]
See comment

**Review by atrefonas — CHANGES_REQUESTED** [review]
Change to 

```
const [openOrdersData, setOpenOrdersData] = useState([])

useMemo(() => {
 const _formattedOrders = _orders.map((order) => {
      const _order = {
        ...order,
        price: floatToFixedDisplay(order.price)
      }
      return _order
    })

    setOpenOrdersData(_formattedOrders)
  }, [_orders, setOpenOrdersData])
```

**Review by atrefonas — APPROVED** [review]
